/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import br.ba.funcionario.TelaCadastrarFuncionario;
import br.ba.funcionario.TelaConsultarFuncionario;
import java.awt.Color;

/**
 *
 * @author joaog
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        panPrincipal.setBackground(Color.DARK_GRAY);
        panUsuario.setVisible(false);
        panCity.setVisible(false);
        panVeic.setVisible(false);
        panPass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblVeiculo = new javax.swing.JLabel();
        lblPassagem = new javax.swing.JLabel();
        panUsuario = new javax.swing.JPanel();
        lblCadUser = new javax.swing.JLabel();
        lblConsUser = new javax.swing.JLabel();
        panCity = new javax.swing.JPanel();
        lblCadCity = new javax.swing.JLabel();
        lblConsCity = new javax.swing.JLabel();
        panVeic = new javax.swing.JPanel();
        lblCadVeic = new javax.swing.JLabel();
        lblConsVeic = new javax.swing.JLabel();
        panPass = new javax.swing.JPanel();
        lblCadPas = new javax.swing.JLabel();
        lblConsPas = new javax.swing.JLabel();
        lblVendPas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_UsuárioR.jpg"))); // NOI18N
        panPrincipal.add(jLabel1);
        jLabel1.setBounds(42, 206, 105, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_Veículo.jpg"))); // NOI18N
        panPrincipal.add(jLabel2);
        jLabel2.setBounds(449, 215, 105, 90);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_Cidade1.jpg"))); // NOI18N
        panPrincipal.add(jLabel3);
        jLabel3.setBounds(231, 217, 105, 88);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_Passagem1.jpg"))); // NOI18N
        panPrincipal.add(jLabel4);
        jLabel4.setBounds(660, 220, 105, 90);

        lblUsuario.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Funcionário");
        lblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseExited(evt);
            }
        });
        panPrincipal.add(lblUsuario);
        lblUsuario.setBounds(40, 310, 110, 22);

        lblCidade.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(255, 255, 255));
        lblCidade.setText("Cidades");
        lblCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCidadeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCidadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCidadeMouseExited(evt);
            }
        });
        panPrincipal.add(lblCidade);
        lblCidade.setBounds(247, 314, 70, 22);

        lblVeiculo.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblVeiculo.setText("Veículos");
        lblVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVeiculoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVeiculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVeiculoMouseExited(evt);
            }
        });
        panPrincipal.add(lblVeiculo);
        lblVeiculo.setBounds(463, 314, 75, 22);

        lblPassagem.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblPassagem.setForeground(new java.awt.Color(255, 255, 255));
        lblPassagem.setText("Passagens");
        lblPassagem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPassagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPassagemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPassagemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPassagemMouseExited(evt);
            }
        });
        panPrincipal.add(lblPassagem);
        lblPassagem.setBounds(670, 320, 88, 22);

        panUsuario.setBackground(new java.awt.Color(50, 76, 137));
        panUsuario.setForeground(new java.awt.Color(255, 255, 255));

        lblCadUser.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblCadUser.setForeground(new java.awt.Color(255, 255, 255));
        lblCadUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        lblCadUser.setText("Cadastrar");
        lblCadUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCadUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadUserMouseExited(evt);
            }
        });

        lblConsUser.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblConsUser.setForeground(new java.awt.Color(255, 255, 255));
        lblConsUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        lblConsUser.setText("Consultar");
        lblConsUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblConsUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConsUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConsUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panUsuarioLayout = new javax.swing.GroupLayout(panUsuario);
        panUsuario.setLayout(panUsuarioLayout);
        panUsuarioLayout.setHorizontalGroup(
            panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadUser)
                    .addComponent(lblConsUser))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panUsuarioLayout.setVerticalGroup(
            panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUsuarioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCadUser)
                .addGap(18, 18, 18)
                .addComponent(lblConsUser)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panPrincipal.add(panUsuario);
        panUsuario.setBounds(20, 350, 150, 120);

        panCity.setBackground(new java.awt.Color(50, 76, 137));

        lblCadCity.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblCadCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCadCity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/map_add.png"))); // NOI18N
        lblCadCity.setText("Cadastrar");
        lblCadCity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCadCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadCityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadCityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadCityMouseExited(evt);
            }
        });

        lblConsCity.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblConsCity.setForeground(new java.awt.Color(255, 255, 255));
        lblConsCity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        lblConsCity.setText("Consultar");
        lblConsCity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblConsCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsCityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConsCityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConsCityMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panCityLayout = new javax.swing.GroupLayout(panCity);
        panCity.setLayout(panCityLayout);
        panCityLayout.setHorizontalGroup(
            panCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsCity)
                    .addComponent(lblCadCity))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panCityLayout.setVerticalGroup(
            panCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCityLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCadCity)
                .addGap(18, 18, 18)
                .addComponent(lblConsCity)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panPrincipal.add(panCity);
        panCity.setBounds(220, 350, 150, 120);

        panVeic.setBackground(new java.awt.Color(50, 76, 137));

        lblCadVeic.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblCadVeic.setForeground(new java.awt.Color(255, 255, 255));
        lblCadVeic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car_add.png"))); // NOI18N
        lblCadVeic.setText("Cadastrar");
        lblCadVeic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCadVeic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadVeicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadVeicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadVeicMouseExited(evt);
            }
        });

        lblConsVeic.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblConsVeic.setForeground(new java.awt.Color(255, 255, 255));
        lblConsVeic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        lblConsVeic.setText("Consultar");
        lblConsVeic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblConsVeic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsVeicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConsVeicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConsVeicMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panVeicLayout = new javax.swing.GroupLayout(panVeic);
        panVeic.setLayout(panVeicLayout);
        panVeicLayout.setHorizontalGroup(
            panVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVeicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadVeic)
                    .addComponent(lblConsVeic))
                .addGap(34, 34, 34))
        );
        panVeicLayout.setVerticalGroup(
            panVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVeicLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCadVeic)
                .addGap(18, 18, 18)
                .addComponent(lblConsVeic)
                .addGap(30, 30, 30))
        );

        panPrincipal.add(panVeic);
        panVeic.setBounds(430, 350, 150, 120);

        panPass.setBackground(new java.awt.Color(50, 76, 137));

        lblCadPas.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblCadPas.setForeground(new java.awt.Color(255, 255, 255));
        lblCadPas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vcard_add.png"))); // NOI18N
        lblCadPas.setText("Cadastrar");
        lblCadPas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCadPas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadPasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadPasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadPasMouseExited(evt);
            }
        });

        lblConsPas.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblConsPas.setForeground(new java.awt.Color(255, 255, 255));
        lblConsPas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        lblConsPas.setText("Consultar");
        lblConsPas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblConsPas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsPasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConsPasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConsPasMouseExited(evt);
            }
        });

        lblVendPas.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblVendPas.setForeground(new java.awt.Color(255, 255, 255));
        lblVendPas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vcard.png"))); // NOI18N
        lblVendPas.setText("Vender");
        lblVendPas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblVendPas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVendPasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVendPasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVendPasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panPassLayout = new javax.swing.GroupLayout(panPass);
        panPass.setLayout(panPassLayout);
        panPassLayout.setHorizontalGroup(
            panPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsPas)
                    .addComponent(lblCadPas)
                    .addComponent(lblVendPas))
                .addGap(34, 34, 34))
        );
        panPassLayout.setVerticalGroup(
            panPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPassLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCadPas)
                .addGap(18, 18, 18)
                .addComponent(lblVendPas)
                .addGap(18, 18, 18)
                .addComponent(lblConsPas)
                .addContainerGap())
        );

        panPrincipal.add(panPass);
        panPass.setBounds(650, 350, 150, 160);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_logo_PasSystem.jpg"))); // NOI18N
        panPrincipal.add(jLabel6);
        jLabel6.setBounds(280, 30, 200, 150);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_out.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panPrincipal.add(jButton1);
        jButton1.setBounds(703, 580, 80, 25);

        lblTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela_Principal.jpg"))); // NOI18N
        panPrincipal.add(lblTela);
        lblTela.setBounds(0, 0, 850, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseClicked
        // TODO add your handling code here:
        lblUsuario.setForeground(Color.blue);
        panCity.setVisible(false);
        panVeic.setVisible(false);
        panPass.setVisible(false);
        panUsuario.setVisible(true);
        
    }//GEN-LAST:event_lblUsuarioMouseClicked

    private void lblCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCidadeMouseClicked
        lblCidade.setForeground(Color.BLUE);
        panUsuario.setVisible(false);
        panVeic.setVisible(false);
        panPass.setVisible(false);
        panCity.setVisible(true);
    }//GEN-LAST:event_lblCidadeMouseClicked

    private void lblVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVeiculoMouseClicked
        lblVeiculo.setForeground(Color.blue);
        panUsuario.setVisible(false);
        panPass.setVisible(false);
        panCity.setVisible(false);
        panVeic.setVisible(true);
    }//GEN-LAST:event_lblVeiculoMouseClicked

    private void lblPassagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassagemMouseClicked
        lblPassagem.setForeground(Color.blue);
        panUsuario.setVisible(false);
        panCity.setVisible(false);
        panVeic.setVisible(false);
        panPass.setVisible(true);
    }//GEN-LAST:event_lblPassagemMouseClicked

    private void lblCadUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadUserMouseClicked
       new TelaCadastrarFuncionario().setVisible(true);
       dispose();
    }//GEN-LAST:event_lblCadUserMouseClicked

    private void lblConsUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsUserMouseClicked
        lblConsUser.setForeground(Color.BLUE);
        new TelaConsultarFuncionario().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblConsUserMouseClicked

    private void lblUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseEntered
        lblUsuario.setForeground(Color.yellow);
    }//GEN-LAST:event_lblUsuarioMouseEntered

    private void lblUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseExited
        lblUsuario.setForeground(Color.white);
    }//GEN-LAST:event_lblUsuarioMouseExited

    private void lblCadUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadUserMouseEntered
        lblCadUser.setForeground(Color.yellow);
    }//GEN-LAST:event_lblCadUserMouseEntered

    private void lblCadUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadUserMouseExited
        lblCadUser.setForeground(Color.white);
    }//GEN-LAST:event_lblCadUserMouseExited

    private void lblConsUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsUserMouseEntered
        lblConsUser.setForeground(Color.yellow);
    }//GEN-LAST:event_lblConsUserMouseEntered

    private void lblConsUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsUserMouseExited
        lblConsUser.setForeground(Color.white);
    }//GEN-LAST:event_lblConsUserMouseExited

    private void lblCidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCidadeMouseEntered
        lblCidade.setForeground(Color.yellow);
    }//GEN-LAST:event_lblCidadeMouseEntered

    private void lblCidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCidadeMouseExited
        lblCidade.setForeground(Color.white);
    }//GEN-LAST:event_lblCidadeMouseExited

    private void lblCadCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadCityMouseClicked
        lblCadCity.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblCadCityMouseClicked

    private void lblCadCityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadCityMouseEntered
        lblCadCity.setForeground(Color.yellow);
    }//GEN-LAST:event_lblCadCityMouseEntered

    private void lblCadCityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadCityMouseExited
        lblCadCity.setForeground(Color.white);
    }//GEN-LAST:event_lblCadCityMouseExited

    private void lblConsCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsCityMouseClicked
       lblConsCity.setForeground(Color.blue);
    }//GEN-LAST:event_lblConsCityMouseClicked

    private void lblConsCityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsCityMouseEntered
       lblConsCity.setForeground(Color.yellow);
    }//GEN-LAST:event_lblConsCityMouseEntered

    private void lblConsCityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsCityMouseExited
       lblConsCity.setForeground(Color.white);
    }//GEN-LAST:event_lblConsCityMouseExited

    private void lblVeiculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVeiculoMouseEntered
        lblVeiculo.setForeground(Color.yellow);
    }//GEN-LAST:event_lblVeiculoMouseEntered

    private void lblVeiculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVeiculoMouseExited
        lblVeiculo.setForeground(Color.white);
    }//GEN-LAST:event_lblVeiculoMouseExited

    private void lblCadVeicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadVeicMouseClicked
        lblCadVeic.setForeground(Color.blue);
    }//GEN-LAST:event_lblCadVeicMouseClicked

    private void lblCadVeicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadVeicMouseEntered
        lblCadVeic.setForeground(Color.yellow);
    }//GEN-LAST:event_lblCadVeicMouseEntered

    private void lblCadVeicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadVeicMouseExited
        lblCadVeic.setForeground(Color.white);
    }//GEN-LAST:event_lblCadVeicMouseExited

    private void lblConsVeicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsVeicMouseClicked
        lblConsVeic.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblConsVeicMouseClicked

    private void lblConsVeicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsVeicMouseEntered
        lblConsVeic.setForeground(Color.yellow);
    }//GEN-LAST:event_lblConsVeicMouseEntered

    private void lblConsVeicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsVeicMouseExited
        lblConsVeic.setForeground(Color.white);
    }//GEN-LAST:event_lblConsVeicMouseExited

    private void lblPassagemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassagemMouseEntered
        lblPassagem.setForeground(Color.yellow);
    }//GEN-LAST:event_lblPassagemMouseEntered

    private void lblPassagemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassagemMouseExited
        lblPassagem.setForeground(Color.white);
    }//GEN-LAST:event_lblPassagemMouseExited

    private void lblCadPasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadPasMouseClicked
        lblCadPas.setForeground(Color.blue);
    }//GEN-LAST:event_lblCadPasMouseClicked

    private void lblCadPasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadPasMouseEntered
        lblCadPas.setForeground(Color.yellow);
    }//GEN-LAST:event_lblCadPasMouseEntered

    private void lblCadPasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadPasMouseExited
        lblCadPas.setForeground(Color.white);
    }//GEN-LAST:event_lblCadPasMouseExited

    private void lblConsPasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsPasMouseClicked
        lblConsPas.setForeground(Color.blue);
    }//GEN-LAST:event_lblConsPasMouseClicked

    private void lblConsPasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsPasMouseEntered
        lblConsPas.setForeground(Color.yellow);
    }//GEN-LAST:event_lblConsPasMouseEntered

    private void lblConsPasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsPasMouseExited
        lblConsPas.setForeground(Color.white);
    }//GEN-LAST:event_lblConsPasMouseExited

    private void lblVendPasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendPasMouseClicked
        lblVendPas.setForeground(Color.blue);
    }//GEN-LAST:event_lblVendPasMouseClicked

    private void lblVendPasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendPasMouseEntered
        lblVendPas.setForeground(Color.yellow);
    }//GEN-LAST:event_lblVendPasMouseEntered

    private void lblVendPasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendPasMouseExited
        lblVendPas.setForeground(Color.white);
    }//GEN-LAST:event_lblVendPasMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCadCity;
    private javax.swing.JLabel lblCadPas;
    private javax.swing.JLabel lblCadUser;
    private javax.swing.JLabel lblCadVeic;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblConsCity;
    private javax.swing.JLabel lblConsPas;
    private javax.swing.JLabel lblConsUser;
    private javax.swing.JLabel lblConsVeic;
    private javax.swing.JLabel lblPassagem;
    private javax.swing.JLabel lblTela;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVeiculo;
    private javax.swing.JLabel lblVendPas;
    private javax.swing.JPanel panCity;
    private javax.swing.JPanel panPass;
    private javax.swing.JDesktopPane panPrincipal;
    private javax.swing.JPanel panUsuario;
    private javax.swing.JPanel panVeic;
    // End of variables declaration//GEN-END:variables
}
